### ISSUE TITLE
Final (?) to-do list

### ISSUE THREAD

**Issue by catavallejos** [VallejosGroup/BASiCSWorkflow#35]
Adding this here as not everything has been documented in individual issues. 

Note: 🔴 marks things that require changes in the `BASiCS` library. 

- [x] Revise abstract
- [x] Revise introduction section. Particularly focus on *intro to BASiCS* paragraph. Yes, in general UMIs are preferable, but our model is not a NB distribution (we have two sources of over-dispersion). Also, UMI protocols tend to be sparser and some may not work well with BASiCS (e.g. snRNAseq). 
- [x] Run chains with EB prior -> in progress by @Alanocallaghan 
- [x] Upload EB chains to gitlab
- [x] Update workflow code to use EB chains
- [x] Add EB option in param description for `BASiCS_MCMC` #33 
- [x] Re-run chains with a seed and update seed in workflow.
- [x] Add ref for EB. http://www.biostat.jhsph.edu/~fdominic/teaching/bio656/labs/labs09/Casella.EmpBayes.pdf
- [x] Edit caption for `dispersion-vs-mean` figure. #37 ?
- [x] Edit HVG/LVG to use threshold directly on epsilon ? 🔴  See https://github.com/catavallejos/BASiCS/pull/203
- [x] Edit caption/size for figure `plot-example-vg-naive`. Potentially remove function. 
- [x] Current version removes diff over-dispersion testing as we want to encourage residual over-dispersion instead. If left like that, add a brief sentence to say that it's possible. OK?
- [x] Look for another workflow to reference for GO analysis. https://f1000research.com/articles/5-1281/v3
- [x] Edit caption and size for `visualise-DE-plot` plot. I tried, but the use of `cowplot` within `BASiCS_PlotDE` doesn't enable me to change some of the figure settings (e.g. legend text size). See https://github.com/catavallejos/BASiCS/issues/200 🔴 
- [x] Change plots in diff testing section to use denoised counts. 
- ~Use a version of `BASiCS_DenoisedCounts` that excludes spike-ins 🔴. See https://github.com/catavallejos/BASiCS/issues/196~ *This is no longer needed*.
- [x] Update figs for diff variability testing. Heatmap temporarily stayed, but a better visualisation is required. Some high level intrerpretation needs to be writen. 
- [x] Review and update no-spikes section once EB chains are ready. 
- [x] Remove ESS from no-spikes section? We can just refer to what was done before. 
- [x] Add ref to 'stable genes' paper. See [here](https://watermark.silverchair.com/giz106.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAArMwggKvBgkqhkiG9w0BBwagggKgMIICnAIBADCCApUGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM2JFY3dK1sFMeeUQVAgEQgIICZqXinecwPIoX2bGpS38s8spND6Wd1KNHlowZb8dZWgt56ki_hHLiSPy714voov9mXOR_ty_iLP3YIRawpM_yVQ-PobsBXrfVATKhBy0yRnTiPWb9jDbrm_RHFM31Bo4DFiCDo9-VlGeDwqVhfn7xgRa-oXA-Pbx5A7BVwMY2e4KiyFEdMY3GVREH4iy6WRv5-Alf81P3npoO3POS5gAHExFregIcUXKKLmW5QwHotyFFbF3HVAc7cytLTzYfrihBPwi7hDM3jTmYqfaU3lmWH9lAsGoaI1UxEl6zTHUfYWqj4IEWTv8BGat9DqUW75LHn3Lbsa17Yf8v8kkQYqthlEyPwo3Qu7Nug-kGUeJ3v3lNvjKQZBjJcDR2jW7qwYlOU33gEsxsEQWJJhvtdRnkEz7PQgKQcHUpeCdsSRApq1Likkk-l116NHPVK_Nw5GsNUBtKkCaxd-kjzzVExMybCJA8f2XswcCcrksBMEbuxFJq62lr7Fz3I50MkBmt3l8qfPZEWuUHzeAhuXzORnwCBJTo_Kggw4Ht0iRD4D0MSO-LMTOtx4GrmCrlokseGnxBFsupplGd_ssNXoIXx13i-cOpb6SRYYNu86crJjx8YM3XJi-kD4l6S0HnfMql2UfWWjK5c7S7UaWv9j6zl7Um6IKM94YVbrMYBLSFRj4TCGwZLE6oDT0Y1vhe3FCcI5qNfhbWBibhd55F_RAswAQXeg4vQB3A02CalWJmsLupFpfpsnTU2Dm-0F8b7GzpqxunetRlaV9O7cXthWcpXSVc0yBK2jDoBAKuUeB3ixgSCeO8wpXb78pC). (guess you mean [here](https://academic.oup.com/gigascience/article/8/9/giz106/5570567))
- [x] Remove uses of `@` operator
