### ISSUE TITLE
Final edits - to-do

### ISSUE THREAD

**Issue by catavallejos** [VallejosGroup/BASiCSWorkflow#36]
- [x] Run MCMC with longer number of iterations
- [x] Update workflow to use new chains (update code + text + running times)
- [x] Update running times with times provided by @Alanocallaghan 
- [x] Update documentation for `PriorMu`/`PriorParam` 
- [x] Geweke: why are there red lines at +-3? What do they signify? (explain in Fig caption)
- [x] Once convergence/ESS is checked in longer chains, merge Figs 7 and 8 focusing on naive cells only. Update associated text.
- [x] Fig 9. Use same x and y-axes in similar panels (?) -> **Not critical, likely to leave as is**
- [x] Remove description of `PercentileThreshold`
- [x] Fig 10, change `NA` label to `Not HVG/LVG`. 
- [x] Edit x- and y-labels in Fig 5 (it's per gene, not cell!)
- [x] Update lines 823-824 to use `chain_naive.Rds` and `chain_active.Rds` once final chains are in gitlab
~- [ ] In QC section, make a comment about the sparsity of the data~
- [x] Edit examples in diff variability section
