### ISSUE TITLE
submission checklist

### ISSUE THREAD

**Issue by alanocallaghan** [VallejosGroup/BASiCSWorkflow#39]
- [x] article type: "software tool article"?
- [x] Publish repo, formerly #38 
- [x] author contributions (entered as below)
  - aoc: Conceptualization, Software, Visualization, Writing – Original Draft Preparation
  - ne:  Conceptualization, Methodology, Software, Writing – Original Draft Preparation, Writing – Review & Editing
  - jcm: Project Administration, Supervision, Writing – Review & Editing
  - cav (corresponding):  Conceptualization, Project Administration, Software, Supervision, Visualization, Writing – Original Draft Preparation, Writing – Review & Editing
- [x] enter funding bodies/grant nos
- [ ] payment information (eventually, presumably...)
- [x] cover letter
- [x] gateway: [bioc](https://f1000research.com/bioconductor)
- [x] final run in Cata's laptop to ensure reproducibility -> Nils to run
- [x] propose reviewers
