### ISSUE TITLE
F1000Research to-do list

### ISSUE THREAD

**Issue by catavallejos** [VallejosGroup/BASiCSWorkflow#41]
- [x] Add Zenodo link / DOI to .bib file 
- [x] Cite Zenodo code within the article: line 221
- [x] Edit *Operation* section to include system requirements and link to Docker. See example [here](https://f1000research.com/articles/10-344) 
- [x] Re-structure *Methods* to have *Implementation* and *Operation* subsections -> **Done / @Alanocallaghan  to review**
- [x] @Alanocallaghan to review *Software availability* section
- [x] Is the Docker public? I am also asked to login in order to access it
- [x] Provide payment information -> only @Alanocallaghan can do this
