### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by catavallejos** [VallejosGroup/BASiCSWorkflow#47]
# Reviewer 1

- [ ] Schematic figure (see discussion in #45)
- [ ] Check enough comments are provided throughout the text
- [ ] See what can we do about ggplot2 
- [ ] Explain EB and other elements of the prior. Would it be better to have a supp section with more details?
- [ ] Create supp section for visualising HPDs etc (mention in text)
- [ ] Check volcano plots concentration around 0.5, calibration?
- [ ] Add @Marx2021] and @Aijo2019] to bibtex 
- [ ] check all libraries are loaded at the start
- [ ] Finish incomplete sentence in rebuttal about PCA axis
- [ ] Check PR about spike-in calculation
